name: test_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.10.5=py310h06a4308_0
  - cffi=1.17.1=py310h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.0.85=hf384b4a_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.0=3
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=6.1.1=hc01ab50_4
  - filelock=3.17.0=py310h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jinja2=3.1.6=py310h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.8.1=h13d4d48_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.15.1.6=h2e68323_0
  - libcurand=10.4.0.35=h50d9014_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - networkx=3.4.2=py310h06a4308_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.18=hd6dcaed_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py310hac6e08b_1
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.18=h1a3bd86_0
  - pytorch=2.2.2=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py310h5eee18b_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py310h06a4308_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - sympy=1.14.0=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=2.2.2=py310_cu121
  - torchtriton=2.2.0=py310
  - torchvision=0.17.2=py310_cu121
  - typing_extensions=4.15.0=py310h06a4308_0
  - urllib3=2.5.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
    - absl-py==2.3.1
    - accelerate==0.28.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.0
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - async-timeout==5.0.1
    - attrs==25.4.0
    - chardet==5.2.0
    - click==8.3.0
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - dataproperty==1.1.0
    - datasets==2.18.0
    - dill==0.3.8
    - evaluate==0.4.6
    - frozenlist==1.8.0
    - fsspec==2024.2.0
    - gitdb==4.0.12
    - gitpython==3.1.45
    - hf-xet==1.1.10
    - huggingface-hub==0.35.3
    - humanfriendly==10.0
    - joblib==1.5.2
    - jsonlines==4.0.0
    - lm-eval==0.4.9.1
    - lxml==6.0.2
    - mbstrdecoder==1.1.4
    - more-itertools==10.8.0
    - multidict==6.7.0
    - multiprocess==0.70.16
    - nltk==3.9.2
    - numexpr==2.13.1
    - numpy==1.26.4
    - optimum==1.17.0
    - packaging==25.0
    - pandas==2.3.3
    - pathvalidate==3.3.1
    - peft==0.10.0
    - platformdirs==4.5.0
    - portalocker==3.2.0
    - propcache==0.4.1
    - protobuf==6.32.1
    - psutil==7.1.0
    - pyarrow==21.0.0
    - pyarrow-hotfix==0.7
    - pybind11==3.0.1
    - pydantic==2.12.0
    - pydantic-core==2.41.1
    - pytablewriter==1.2.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - regex==2025.9.18
    - rouge-score==0.1.2
    - sacrebleu==2.5.1
    - safetensors==0.6.2
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - sentencepiece==0.2.1
    - sentry-sdk==2.41.0
    - six==1.17.0
    - smmap==5.0.2
    - sqlitedict==2.1.0
    - tabledata==1.3.4
    - tabulate==0.9.0
    - tcolorpy==0.1.7
    - threadpoolctl==3.6.0
    - tokenizers==0.22.1
    - tqdm==4.67.1
    - tqdm-multiprocess==0.0.11
    - transformers==4.57.0
    - typepy==1.3.4
    - typing-inspection==0.4.2
    - tzdata==2025.2
    - wandb==0.22.2
    - word2number==1.1
    - xxhash==3.6.0
    - yarl==1.22.0
    - zstandard==0.25.0
prefix: /home/sts/.conda/envs/test_env
